-- Step 3: Supabase pgvector setup for the portfolio RAG chatbot.
--
-- Embeddings are expected to come from OpenAI text-embedding-3-small,
-- which returns 1536 dimensions by default.

create schema if not exists extensions;

create extension if not exists vector with schema extensions;

create table if not exists public.portfolio_chunks (
  id bigint generated by default as identity primary key,
  content text not null,
  embedding extensions.vector(1536) not null,
  source_file text not null,
  project_name text,
  section_title text,
  chunk_index integer not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint portfolio_chunks_source_file_chunk_index_key
    unique (source_file, chunk_index),
  constraint portfolio_chunks_chunk_index_non_negative
    check (chunk_index >= 0),
  constraint portfolio_chunks_metadata_is_object
    check (jsonb_typeof(metadata) = 'object')
);

comment on table public.portfolio_chunks is
  'Approved portfolio knowledge chunks and embeddings for the portfolio RAG chatbot.';

comment on column public.portfolio_chunks.content is
  'Markdown chunk text used as source context for chatbot answers.';

comment on column public.portfolio_chunks.embedding is
  '1536-dimensional OpenAI text-embedding-3-small vector for this chunk.';

comment on column public.portfolio_chunks.source_file is
  'Relative path to the approved markdown source file inside portfolio-knowledge.';

comment on column public.portfolio_chunks.project_name is
  'Optional project, experience, course, or portfolio topic label for source attribution.';

comment on column public.portfolio_chunks.section_title is
  'Nearest markdown heading used to identify where the chunk came from.';

comment on column public.portfolio_chunks.chunk_index is
  'Zero-based chunk number within a source_file, used for idempotent ingestion.';

comment on column public.portfolio_chunks.metadata is
  'Additional non-secret chunk metadata for filtering or source labels.';

alter table public.portfolio_chunks enable row level security;

-- Keep table access private by default. Future server-side code should use
-- SUPABASE_SERVICE_ROLE_KEY from a backend-only environment variable.

create index if not exists portfolio_chunks_embedding_hnsw_idx
  on public.portfolio_chunks
  using hnsw (embedding extensions.vector_cosine_ops);

create index if not exists portfolio_chunks_source_file_idx
  on public.portfolio_chunks (source_file);

create index if not exists portfolio_chunks_project_name_idx
  on public.portfolio_chunks (project_name);

create or replace function public.match_portfolio_chunks (
  query_embedding extensions.vector(1536),
  match_count integer default 5,
  similarity_threshold double precision default 0.5
)
returns table (
  id bigint,
  content text,
  source_file text,
  project_name text,
  section_title text,
  chunk_index integer,
  metadata jsonb,
  similarity double precision
)
language sql
stable
as $$
  select
    pc.id,
    pc.content,
    pc.source_file,
    pc.project_name,
    pc.section_title,
    pc.chunk_index,
    pc.metadata,
    1 - (pc.embedding operator(extensions.<=>) query_embedding) as similarity
  from public.portfolio_chunks as pc
  where
    1 - (pc.embedding operator(extensions.<=>) query_embedding)
      >= coalesce(similarity_threshold, 0.5)
  order by pc.embedding operator(extensions.<=>) query_embedding
  limit least(greatest(coalesce(match_count, 5), 0), 20);
$$;

comment on function public.match_portfolio_chunks(
  extensions.vector(1536),
  integer,
  double precision
) is
  'Returns the most relevant portfolio chunks for a query embedding using cosine similarity.';
